### ISSUE TITLE
Las llamadas que hace la interfaz a la "API" para obtener los datos de la instalación de WP muestran el ID en la URL

### ISSUE THREAD

**Issue by acosatom** [Parkteknia/wp_monitor#17]
Creo que sería conveniente ocultar el ID en la URL independientemente de que las llamadas sean internas.

**Comment by P3r4nD** [comment]
Básicamente he añadido:

- Función en los archivos wpm_cron_plesk y wpm_cron_cpanel para generar un código aleatorio:
`generate_unique_wp_id() {
    echo $(openssl rand -hex 10)
}`

- En los mismos archivos se cambia la forma en que se guarda para cada instalación WP el archivo id.json que ahora se guarda id-code.json. Code es el nuevo ID que usaremos en la interfaz.
- También se añade en wpm_data el archivo wp_id_code_map.json, el cual guardará un mapeo {id: code} para control en cada ejecución del CRON.
- Diversas actualizaciones y modificaciones en WPMonitor.php y WPMonitorApi.php, así como en wpm.js

**Comment by acosatom** [comment]
Me parece aceptable.

**Comment by acosatom** [comment]
Después de estos cambios, puesto que la columna ID ya no se usa, el selector de celda que obtenía la url del dominio a inspeccionar, no es válido. Línea 170 de wpms.js debe ser 0:

`var cell_title = row.getElementsByTagName("td")[1];`

Por lo que al consultar los logs da un error.
