### ISSUE TITLE
¿Algunas variables del config podrían ser seteadas desde el install.sh?

### ISSUE THREAD

**Issue by acosatom** [Parkteknia/wp_monitor#25]
Buenas @P3r4nD !

Estoy revisando y por ejemplo `app_reload_time` hay que configurarla manualmente en config.json. Y aunque tiene asignado por defecto 60000 ms, igual algún usuario quiere cambiarlo en el momento de la instalación.

Es una sugerencia!

Otra cosa es que no tengo muy clara: ¿Cuál es la necesidad de `default_range_type`?

**Comment by P3r4nD** [comment]
# Añadir `app_reload_time` al install.sh
## Descripción
Se debe añadir la configuración de `app_reload_time` como un paso más en la configuración mediante install.sh

## Checklist
- [x] Configurar app_reload_time desde install.sh

**Comment by P3r4nD** [comment]
> default_range_type

Para cuando se llame` readLogByDate($log_data, $timeframe=False)` sin el parámetro $timeframe, por defecto le asigne `default_range_type`.
