### ISSUE TITLE
¿Un temporizador en wpm_jobs_service.service y la opción "confirmar jobs"?

### ISSUE THREAD

**Issue by acosatom** [Parkteknia/wp_monitor#26]
No se hasta que punto sería menos "agresivo" que el servicio para jobs disponga de un `timer`, o al menos la opción. En caso de que el usuario guarde un job erróneo no tendrá tiempo de deshacer...

También podría ser interesante que al guardar un job haya una ventana de confirmación.

**Comment by P3r4nD** [comment]
Pensé en poner un `timer`, pero de hecho, si te fijas, en wpm_jobs.sh hay un while infinito y al final del mismo un sleep(5) segundos. De alguna forma consideré esto como un "temporizador", no crees?

Lo de poner la ventana de confirmación al presionar "Save jobs" está claro y lo veo bien.

**Comment by acosatom** [comment]
Tienes razón! Aunque el sleep podría ser incluso algo más largo. Me pregunto que sucederá si se actualizan varias instalaciones a la vez.

**Comment by P3r4nD** [comment]
Pero a ver, el sleep no interfiere. Los jobs que hay en la "cola" se ejecutan secuencialmente, hasta que no ha terminado un job (WP-Toolkit termina una ejecución) no pasa al siguiente.

Una vez termina todos los jobs, además hace esa pausa de 5 segundos para volver a iterar el while principal.

Aunque revisando esto he visto que si hay  un problema, concretamente en el lock, de hecho faltaría otro más.

Si te parece @acosatom cierra esta issue y yo abriré una nueva con lo que comento del lock.

**Comment by P3r4nD** [comment]
Si te parece @acosatom incluye tu la confirmación de "Save jobs" y yo me pongo con #29
