### ISSUE TITLE
No existe wp_monitor.lock

### ISSUE THREAD

**Issue by acosatom** [Parkteknia/wp_monitor#27]
Estoy revisando la ejecución de jobs y falla ya que no existe wpm_data/tmp/wp_monitor.lock

Se perdió por el camino? :blush:

**Comment by P3r4nD** [comment]
Se quedó lockeado de parranda!! Do it!

**Comment by acosatom** [comment]
Ralmente el problema es otro, en WPMonitor.php tenemos:

```php
$this->cleanTMP($tempDir);
```
Que es llamado al final de `readWPLogs()` para limpiar los archivos temporales en el proceso de descompresión.

Puesto que cada llamada "reload/update" de la interfaz llama a `readWPLogs()` los estaba eliminado.

He añadido

```php
$this->protectedFiles = ["jobs.lock", "wpm_jobs.lock"];
```
y luego
```php
/**
    * Clean tmp files after decompress logs
    *
    */
    public function cleanTMP($tempDir) {
        // After finished working with the extracted files, delete the temporary directory
        $files = glob($this->appData."/tmp/*"); // Get all files in the temporary directory
        foreach ($files as $file) { // Delete each tmp file
            if (is_file($file) && !in_array(basename($file), $this->protectedFiles)) {
                unlink($file);
            }
        }
    }
```
Los cambios se efectuan junto a #29

**Comment by P3r4nD** [comment]
Ralmente el problema es otro, en WPMonitor.php tenemos:
```php
$this->cleanTMP($tempDir);
```
Que es llamado al final de readWPLogs() para limpiar los archivos temporales en el proceso de descompresión.

Puesto que cada llamada "reload/update" de la interfaz llama a readWPLogs() los estaba eliminado.

He añadido
```php
$this->protectedFiles = ["jobs.lock", "wpm_jobs.lock"];
```

y luego
```php
/**
    * Clean tmp files after decompress logs
    *
    */
    public function cleanTMP($tempDir) {
        // After finished working with the extracted files, delete the temporary directory
        $files = glob($this->appData."/tmp/*"); // Get all files in the temporary directory
        foreach ($files as $file) { // Delete each tmp file
            if (is_file($file) && !in_array(basename($file), $this->protectedFiles)) {
                unlink($file);
            }
        }
    }
```

Los cambios se efectuan junto a https://github.com/Parkteknia/wp_monitor/issues/29
