### ISSUE TITLE
Error en wpm_jobs.sh

### ISSUE THREAD

**Issue by acosatom** [Parkteknia/wp_monitor#28]
JOBS_FILE="/opt/wp_monitor/wp_monitor/jobs"

Está repetido wp_monitor! :blush:

**Comment by P3r4nD** [comment]
El error está en la línea 171 del install.sh, $BASE_DIR ya contiene wp_monitor o el directorio principal.

`sed -i "s|^JOBS_FILE=.*|JOBS_FILE=\"$BASE_DIR/wp_monitor/jobs\"|" "$WPM_JOBS_FILE"`

Corregido!

**Comment by P3r4nD** [comment]
El error tiene que estar en install.sh. Te aparece el path mal después de instalar? Ya que en wpm_jobs.sh está bien!

**Comment by P3r4nD** [comment]
Efectivamente está en insall.sh el problema. En la línea 171. Lo edito.
