### ISSUE TITLE
Problema de posible escritura concurrente en el archivo jobs

### ISSUE THREAD

**Issue by P3r4nD** [Parkteknia/wp_monitor#29]
En ` wpm_jobs.sh` usamos flock para que no pueda ejecutarse más de una vez el script, para ello usamos el archivo de bloqueo`wpm_data/tmp/wp_monitor.lock`.

Pero, que ocurrirá si, mientras se está ejecutando ` wpm_jobs.sh`, es decir leyendo línea a línea el archivo `jobs` y desde la interfaz se envían nuevos jobs, es decir se escribe en jobs? Creo que pueden haber problemas!

La solución es añadir otro lock a jobs, y este manejarlo tanto desde el bash como desde PHP.

**Comment by acosatom** [comment]
#33
